import "./styles/globals.css"
import { Poppins, Roboto } from "next/font/google"
import { SessionProvider } from "next-auth/react"
import AuthProvider from "./components/AuthProvider/AuthProvider"

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--poppins-font",
  display: "swap",
  subsets: ["latin"],
})

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  variable: "--roboto-font",
  display: "swap",
  subsets: ["latin"],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${poppins.variable} ${roboto.variable}`}>
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  )
}
